version: "3.9"

services:
  db:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: price_match
      MYSQL_USER: app
      MYSQL_PASSWORD: app123456
    ports:
      - "3306:3306" # 本机需要直连时保留；仅容器间访问可删
    volumes:
      - pm-mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-u",
          "root",
          "-p123456",
        ]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    image: price-match:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      GIN_MODE: release
    volumes:
      - ./configs:/app/configs:ro
    ports:
      - "8080:8080"

volumes:
  pm-mysql-data:
