env: dev

server:
  port: 8080

database:
  type: mysql
  mysql_local: "root:123456@tcp(127.0.0.1:3306)/price_match?charset=utf8mb4&parseTime=True&loc=Local"
  mysql_docker: "app:app123456@tcp(db:3306)/price_match?charset=utf8mb4&parseTime=True&loc=Local"
